name: C++ Syntax Check

on: pull_request

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    steps:

      - name: Configure Build
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . 

      - name: Build
        run: make

      - name: Run Clang-Tidy
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          for file in ${{ steps.changed_files.outputs.changed_cpp_files }}; do
            clang-tidy -p . $file --fix # -p . assumes compile_commands.json is in root
          done

      - name: Skip check (no changes)
        if: steps.check_changes.outputs.has_changes != 'true'
        run: echo "No changed C++ files found. Skipping syntax check."