name: Auto Merge Owner PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up C++
        uses: llvm/llvm-project@v0.0.1
        with:
          version: '10'

      - name: Check for changed C++ files
        id: check_files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E '\.cpp$' > changed_files.txt
          if [ ! -s changed_files.txt ]; then
            echo "No C++ files changed. Skipping cppcheck."
            exit 0
          fi
          echo "C++ files changed. Proceeding to run cppcheck."

      - name: Install cppcheck
        if: steps.check_files.outputs.skip != 'true'
        run: sudo apt-get install -y cppcheck

      - name: Run cppcheck
        if: steps.check_files.outputs.skip != 'true'
        run: |
          cppcheck --enable=all --error-exitcode=1 $(cat changed_files.txt)

      - name: Clean up
        run: rm changed_files.txt
