name: C++ Syntax Check

on: pull_request

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed C++ files
        id: changed_files
        run: |
          changed_cpp_files=$(git diff --name-only --diff-filter=d HEAD^ HEAD | grep '\.cpp$' | tr '\n' ' ')
          echo "changed_cpp_files=$changed_cpp_files" >> $GITHUB_OUTPUT

      - name: Check if any C++ files changed
        id: check_changes
        if: steps.changed_files.outputs.changed_cpp_files != ''
        run: echo "::set-output name=has_changes::true"

      - name: Print Working Directory (for debugging)
        run: pwd

      - name: Configure Build
        working-directory: . # Crucial: Set working directory to project root
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .

      - name: Build
        working-directory: . # Same working directory as Configure Build
        run: make

      - name: Run Clang-Tidy
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          for file in ${{ steps.changed_files.outputs.changed_cpp_files }}; do
            clang-tidy -p . $file --fix # -p . assumes compile_commands.json is in root
          done

      - name: Skip check (no changes)
        if: steps.check_changes.outputs.has_changes != 'true'
        run: echo "No changed C++ files found. Skipping syntax check."