name: first action

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: CPP Evaluation
  # You may pin to the exact commit or the version.
  # uses: lukeely/cpp-evaluation-action@db42971265834124c705a5e737ad09cffe335071
        uses: lukeely/cpp-evaluation-action@0.0.1
          
  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
                  
