name: challenge3

on: push

env:
  ARTIFACTNAME: artifact

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACTNAME }}
          path: .